from flask import Flask
from Application.Controllers.countries_controller import countries_controller_api
from Application.Controllers.customers_controller import customers_controller_api
from Application.Controllers.customercompanies_controller import customercompanies_controller_api
from Application.Controllers.customeremployees_controller import customeremployees_controller_api
from Application.Controllers.employments_controller import employments_controller_api
from Application.Controllers.employmentjobs_controller import employmentjobs_controller_api
from Application.Controllers.inventories_controller import inventories_controller_api
from Application.Controllers.locations_controller import locations_controller_api
from Application.Controllers.orderitems_controller import orderitems_controller_api
from Application.Controllers.orders_controller import orders_controller_api
from Application.Controllers.people_controller import people_controller_api
from Application.Controllers.personlocations_controller import personlocations_controller_api
from Application.Controllers.phonenumbers_controller import phonenumbers_controller_api
from Application.Controllers.products_controller import products_controller_api
from Application.Controllers.restrictedinfo_controller import restrictedinfo_controller_api
from Application.Controllers.warehouses_controller import warehouses_controller_api

app = Flask(__name__)

app.register_blueprint(countries_controller_api)
app.register_blueprint(customers_controller_api)
app.register_blueprint(customercompanies_controller_api)
app.register_blueprint(customeremployees_controller_api)
app.register_blueprint(employments_controller_api)
app.register_blueprint(employmentjobs_controller_api)
app.register_blueprint(inventories_controller_api)
app.register_blueprint(locations_controller_api)
app.register_blueprint(orderitems_controller_api)
app.register_blueprint(orders_controller_api)
app.register_blueprint(people_controller_api)
app.register_blueprint(personlocations_controller_api)
app.register_blueprint(phonenumbers_controller_api)
app.register_blueprint(products_controller_api)
app.register_blueprint(restrictedinfo_controller_api)
app.register_blueprint(warehouses_controller_api)


@app.route("/")
def hello():
    return "Hello World!"


if __name__ == "__main__":
    app.run()








